### PR TITLE
Automatically create a release on tag

### PR DESCRIPTION
**Pull request by JssDWt**
Creates an automatic (draft) release when a tag is pushed.
Compiles lspd, cln_plugin and lnd and adds them as release artifacts.
The commit hash and version abbreviation are now also logged on startup of both lspd and the cln_plugin.

### CODE REVIEW

**Review by yaslama — COMMENTED** [review]
In the recent versions of go, one can use go version -m <executable> to see the  commit hash. So we perhaps don't need to store the commit hash and to add the logs

**Comment by JssDWt** [comment]
> In the recent versions of o, one can use go version -m to see the commit hash. So we perhaps don't need to store the commit hash and to add the logs

Here's the output of `go version -m lspd`, run on a local lspd binary of mine:

```
lspd: go1.21.6
        path    github.com/breez/lspd
        mod     github.com/breez/lspd   (devel)
        dep     github.com/GoWebProd/gip        v0.0.0-20230623090727-b60d41d5d320      h1:lddR7TsA0fUX8Kh+oc01z4GwmCoBveT79zhNLK43xLk=
        dep     github.com/GoWebProd/uuid7      v0.0.0-20230623091058-5f5954faed6a      h1:mThF075zgPGTHRfPcRtaHSIKMDAG6Xd82HNazP5yP4I=
        dep     github.com/aead/chacha20        v0.0.0-20180709150244-8b13a72661da      h1:KjTM2ks9d14ZYCvmHS9iAKVt9AyzRSqNU1qabPih5BY=
        dep     github.com/aead/siphash v1.0.1  h1:FwHfE/T45KPKYuuSAKyyvE+oPWcaQ+CUmFW0bPlM+kg=
        dep     github.com/aws/aws-sdk-go       v1.34.0 h1:brux2dRrlwCF5JhTL7MUT3WUwo9zfDHZZp3+g3Mvlmo=
        dep     github.com/btcsuite/btcd        v0.23.5-0.20230905170901-80f5a0ffdf36   h1:g/UbZ6iSzcUH9kEvC+rB8UBCqahmt69e8y6nCegczbg=
        dep     github.com/btcsuite/btcd/btcec/v2       v2.3.2  h1:5n0X6hX0Zk+6omWcihdYvdAlGf2DfasC0GMf7DClJ3U=
        dep     github.com/btcsuite/btcd/btcutil        v1.1.4-0.20230904040416-d4f519f5dc05    h1:aemxF+69pT9sYC5E6Qj71zQVHcF72m0BNcVhCl3/thU=
        dep     github.com/btcsuite/btcd/btcutil/psbt   v1.1.8  h1:4voqtT8UppT7nmKQkXV+T9K8UyQjKOn2z/ycpmJK8wg=
        dep     github.com/btcsuite/btcd/chaincfg/chainhash     v1.0.2  h1:KdUfX2zKommPRa+PD0sWZUyXe9w277ABlgELO7H04IM=
        dep     github.com/btcsuite/btclog      v0.0.0-20170628155309-84c8d2346e9f      h1:bAs4lUbRJpnnkd9VhRV3jjAVU7DJVjMaK+IsvSeZvFo=
        dep     github.com/btcsuite/btcwallet   v0.16.10-0.20231017144732-e3ff37491e9c  h1:+7tbYEUj0TYYIvuvE9YP+x5dU3FT/8J6Qh8d5YvQwrE=
        dep     github.com/btcsuite/btcwallet/wallet/txauthor   v1.3.2  h1:etuLgGEojecsDOYTII8rYiGHjGyV5xTqsXi+ZQ715UU=
        dep     github.com/btcsuite/btcwallet/wallet/txrules    v1.2.0  h1:BtEN5Empw62/RVnZ0VcJaVtVlBijnLlJY+dwjAye2Bg=
        dep     github.com/btcsuite/btcwallet/wallet/txsizes    v1.2.3  h1:PszOub7iXVYbtGybym5TGCp9Dv1h1iX4rIC3HICZGLg=
        dep     github.com/btcsuite/btcwallet/walletdb  v1.4.0  h1:/C5JRF+dTuE2CNMCO/or5N8epsrhmSM4710uBQoYPTQ=
        dep     github.com/btcsuite/btcwallet/wtxmgr    v1.5.0  h1:WO0KyN4l6H3JWnlFxfGR7r3gDnlGT7W2cL8vl6av4SU=
        dep     github.com/btcsuite/go-socks    v0.0.0-20170105172521-4720035b7bfd      h1:R/opQEbFEy9JGkIguV40SvRY1uliPX8ifOvi6ICsFCw=
        dep     github.com/btcsuite/websocket   v0.0.0-20150119174127-31079b680792      h1:R8vQdOQdZ9Y3SkEwmHoWBmX1DNXhXZqlTpq6s4tyJGc=
        dep     github.com/caddyserver/certmagic        v0.11.2 h1:nPBqyuFNHJEf2FwC1ixJjArtTKWyPqpaH6k4jl7gxYI=
        dep     github.com/cenkalti/backoff/v4  v4.1.3  h1:cFAlzYUlVYDysBEH2T5hyJZMh3+5+WCBvSnK6Q8UtC4=
        dep     github.com/davecgh/go-spew      v1.1.1  h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
        dep     github.com/decred/dcrd/crypto/blake256  v1.0.1  h1:7PltbUIQB7u/FfZ39+DGa/ShuMyJ5ilcvdfma9wOH6Y=
        dep     github.com/decred/dcrd/dcrec/secp256k1/v4       v4.2.0  h1:8UrgZ3GkP4i/CLijOJx79Yu+etlyjdBU4sfcs2WYQMs=
        dep     github.com/decred/dcrd/lru      v1.0.0  h1:Kbsb1SFDsIlaupWPwsPp+dkxiBY1frcS07PCPgotKz8=
        dep     github.com/ecies/go/v2  v2.0.8  h1:0tL4KoC57w2WwwG10DiX72sGFi7BGyp/zA5KdUa2UqQ=
        dep     github.com/elementsproject/glightning   v0.0.0-20230525134205-ef34d849f564
        =>      github.com/breez/glightning     v0.0.1-breez.0.20231123140102-d50d43e22138      h1:qNHyE789komFsN62blDo4Gbz5eie65pzkOkZ8UxQZEY=

        dep     github.com/ethereum/go-ethereum v1.13.5 h1:U6TCRciCqZRe4FPXmy1sMGxTfuk8P7u2UoinF3VbaFk=
        dep     github.com/go-acme/lego/v3      v3.7.0  h1:qC5/8/CbltyAE8fGLE6bGlqucj7pXc/vBxiLwLOsmAQ=
        dep     github.com/go-errors/errors     v1.0.1  h1:LUHzmkK3GUKUrL/1gfBUxAHzcev3apQlezX/+O7ma6w=
        dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
        dep     github.com/gorilla/websocket    v1.4.2  h1:+/TMaTYc4QFitKJxsQ7Yye35DkWvkdLcvGKqM+x0Ufc=
        dep     github.com/grpc-ecosystem/go-grpc-middleware    v1.3.0  h1:+9834+KizmvFV7pXQGSXQTsaWhq2GjuNUt0aUU0YBYw=
        dep     github.com/grpc-ecosystem/grpc-gateway/v2       v2.5.0  h1:ajue7SzQMywqRjg2fK7dcpc0QhFGpTR2plWfV4EZWR4=
        dep     github.com/jackc/chunkreader/v2 v2.0.1  h1:i+RDz65UE+mmpjTfyz0MoVTnzeYxroil2G82ki7MGG8=
        dep     github.com/jackc/pgconn v1.14.0 h1:vrbA9Ud87g6JdFWkHTJXppVce58qPIdP7N8y0Ml/A7Q=
        dep     github.com/jackc/pgio   v1.0.0  h1:g12B9UwVnzGhueNavwioyEEpAmqMe1E/BN9ES+8ovkE=
        dep     github.com/jackc/pgpassfile     v1.0.0  h1:/6Hmqy13Ss2zCq62VdNG8tM1wchn8zjSGOBJ6icpsIM=
        dep     github.com/jackc/pgproto3/v2    v2.3.2  h1:7eY55bdBeCz1F2fTzSz69QC+pG46jYq9/jtSPiJ5nn0=
        dep     github.com/jackc/pgservicefile  v0.0.0-20221227161230-091c0ba34f0a      h1:bbPeKD0xmW/Y25WS6cokEszi5g+S0QxI/d45PkRi7Nk=
        dep     github.com/jackc/pgtype v1.14.0 h1:y+xUdabmyMkJLyApYuPj38mW+aAIqCe5uuBB51rH3Vw=
        dep     github.com/jackc/pgx/v4 v4.18.1 h1:YP7G1KABtKpB5IHrO9vYwSrCOhs7p3uqhvhhQBptya0=
        dep     github.com/jackc/pgx/v5 v5.4.3  h1:cxFyXhxlvAifxnkKKdlxv8XqUf59tDlYjnV5YYfsJJY=
        dep     github.com/jackc/puddle/v2      v2.2.1  h1:RhxXJtFG022u4ibrCSMSiu5aOq1i77R3OHKNJj77OAk=
        dep     github.com/jmespath/go-jmespath v0.4.0  h1:BEgLn5cpjn8UN1mAw4NjwDrS35OdebyEtFe+9YPoQUg=
        dep     github.com/jrick/logrotate      v1.0.0  h1:lQ1bL/n9mBNeIXoTUoYRlK4dHuNJVofX9oWqBtPnSzI=
        dep     github.com/juju/loggo   v1.0.0  h1:Y6ZMQOGR9Aj3BGkiWx7HBbIx6zNwNkxhVNOHU2i1bl0=
        dep     github.com/kkdai/bstream        v1.0.0  h1:Se5gHwgp2VT2uHfDrkbbgbgEvV9cimLELwrPJctSjg8=
        dep     github.com/klauspost/cpuid      v1.2.3  h1:CCtW0xUnWGVINKvE/WWOYKdsPV6mawAtvQuSl8guwQs=
        dep     github.com/lightninglabs/gozmq  v0.0.0-20191113021534-d20a764486bf      h1:HZKvJUHlcXI/f/O0Avg7t8sqkPo78HFzjmeYFl6DPnc=
        dep     github.com/lightninglabs/neutrino       v0.16.0 h1:YNTQG32fPR/Zg0vvJVI65OBH8l3U18LSXXtX91hx0q0=
        dep     github.com/lightninglabs/neutrino/cache v1.1.1  h1:TllWOSlkABhpgbWJfzsrdUaDH2fBy/54VSIB4vVqV8M=
        dep     github.com/lightningnetwork/lightning-onion     v1.2.1-0.20230823005744-06182b1d7d2f    h1:Pua7+5TcFEJXIIZ1I2YAUapmbcttmLj4TTi786bIi3s=
        dep     github.com/lightningnetwork/lnd v0.17.2-beta
        =>      github.com/breez/lnd    v0.15.0-beta.rc6.0.20231122093500-0c939786ced7  h1:RLHCG90jBAE8wNCUFMeu7j4LNbXWdV8BOsVZtmsTFpk=

        dep     github.com/lightningnetwork/lnd/clock   v1.1.1  h1:OfR3/zcJd2RhH0RU+zX/77c0ZiOnIMsDIBjgjWdZgA0=
        dep     github.com/lightningnetwork/lnd/healthcheck     v1.2.3  h1:oqhOOy8WmIEa6RBkYKC0mmYZkhl8T2kGD97n9jpML8o=
        dep     github.com/lightningnetwork/lnd/kvdb    v1.4.4  h1:bCv63rVCvzqj1BkagN/EWTov6NDDgYEG/t0z2HepRMk=
        dep     github.com/lightningnetwork/lnd/queue   v1.1.1  h1:99ovBlpM9B0FRCGYJo6RSFDlt8/vOkQQZznVb18iNMI=
        dep     github.com/lightningnetwork/lnd/ticker  v1.1.1  h1:J/b6N2hibFtC7JLV77ULQp++QLtCwT6ijJlbdiZFbSM=
        dep     github.com/lightningnetwork/lnd/tlv     v1.1.1  h1:BW1u9+uHLRA9sm+8FBkAg1H9rPjrj3S9KvXYiCYjQWk=
        dep     github.com/lightningnetwork/lnd/tor     v1.1.2  h1:3zv9z/EivNFaMF89v3ciBjCS7kvCj4ZFG7XvD2Qq0/k=
        dep     github.com/ltcsuite/ltcd        v0.0.0-20190101042124-f37f8bf35796      h1:sjOGyegMIhvgfq5oaue6Td+hxZuf3tDC8lAPrFldqFw=
        dep     github.com/miekg/dns    v1.1.43 h1:JKfpVSCB84vrAmHzyrsxB5NAr5kLoMXZArPSw7Qlgyg=
        dep     github.com/pkg/errors   v0.9.1  h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
        dep     github.com/pmezard/go-difflib   v1.0.0  h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
        dep     github.com/rogpeppe/fastuuid    v1.2.0  h1:Ppwyp6VYCF1nvBTXL3trRso7mXMlRrw9ooo375wvi2s=
        dep     github.com/stretchr/objx        v0.5.0  h1:1zr/of2m5FGMsad5YfcqgdqdWrIhu+EBEJRhR1U7z/c=
        dep     github.com/stretchr/testify     v1.8.4  h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQwehR5yeSVQQcUk=
        dep     github.com/tv42/zbase32 v0.0.0-20220222190657-f76a9fc892fa      h1:2EwhXkNkeMjX9iFYGWLPQLPhw9O58BhnYgtYKeqybcY=
        dep     go.etcd.io/bbolt        v1.3.7  h1:j+zJOnnEjF/kyHlDDgGnVL/AIqIJPq8UoB2GSNfkUfQ=
        dep     golang.org/x/crypto     v0.17.0 h1:r8bRNjWL3GshPW3gkd+RpvzWrZAwPS49OmTGZ/uhM4k=
        dep     golang.org/x/exp        v0.0.0-20230905200255-921286631fa9      h1:GoHiUyI/Tp2nVkLI2mCxVkOjsbSXD66ic0XW0js0R9g=
        dep     golang.org/x/net        v0.17.0 h1:pVaXccu2ozPjCXewfr1S7xza/zcXTity9cCdXQYSjIM=
        dep     golang.org/x/sync       v0.3.0  h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
        dep     golang.org/x/sys        v0.15.0 h1:h48lPFYpsTvQJZF4EKyI4aLHaev3CxivZmv7yZig9pc=
        dep     golang.org/x/term       v0.15.0 h1:y/Oo/a/q3IXu26lQgl04j/gjuBDOBlx7X6Om1j2CPW4=
        dep     golang.org/x/text       v0.14.0 h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=
        dep     google.golang.org/genproto      v0.0.0-20230822172742-b8732ec3820d      h1:VBu5YqKPv6XiJ199exd8Br+Aetz+o08F+PLMnwJQHAY=
        dep     google.golang.org/genproto/googleapis/api       v0.0.0-20230822172742-b8732ec3820d      h1:DoPTO70H+bcDXcd39vOqb2viZxgqeBeSGtZ55yZU4/Q=
        dep     google.golang.org/genproto/googleapis/rpc       v0.0.0-20230822172742-b8732ec3820d      h1:uvYuEyMHKNt+lT4K3bN6fGswmK8qSvcreM3BwjDh+y4=
        dep     google.golang.org/grpc  v1.59.0 h1:Z5Iec2pjwb+LEOqzpB2MR12/eKFhDPhuqW91O+4bwUk=
        dep     google.golang.org/protobuf      v1.31.0
        =>      github.com/lightninglabs/protobuf-go-hex-display        v1.30.0-hex-display     h1:pRdza2wleRN1L2fJXd6ZoQ9ZegVFTAb2bOQfruJPKcY=

        dep     gopkg.in/errgo.v1       v1.0.1  h1:oQFRXzZ7CkBGdm1XZm/EbQYaYNNEElNBOd09M6cqNso=
        dep     gopkg.in/macaroon-bakery.v2     v2.0.1  h1:0N1TlEdfLP4HXNCg7MQUMp5XwvOoxk+oe9Owr2cpvsc=
        dep     gopkg.in/macaroon.v2    v2.0.0  h1:LVWycAfeJBUjCIqfR9gqlo7I8vmiXRr51YEOZ1suop8=
        dep     gopkg.in/square/go-jose.v2      v2.3.1  h1:SK5KegNXmKmqE342YYN2qPHEnUYeoMiXXl1poUlI+o4=
        dep     gopkg.in/yaml.v3        v3.0.1  h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
        build   -buildmode=exe
        build   -compiler=gc
        build   DefaultGODEBUG=panicnil=1
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=arm64
        build   GOOS=darwin
        build   vcs=git
        build   vcs.revision=8ceee6f815b1607c779761b3a523ee74d3cece03
        build   vcs.time=2024-02-02T10:56:22Z
        build   vcs.modified=false
```

It does contain the vcs.revision, so indeed it looks like that might be used somewhere. Do you know how to get that info at runtime?

I do like having the most recent tag in the logs, which is currently done with the `Commit` field. So it would at a glance tell you the tag and whether it's dirty. I don't think there's any way to get that info with `go version -m`

**Comment by yaslama** [comment]
https://pkg.go.dev/debug/buildinfo perhaps vcs.modified is true if the source is different than the commit id

**Comment by JssDWt** [comment]
> https://pkg.go.dev/debug/buildinfo perhaps vcs.modified is true if the source is different than the commit id

With this you need to read the binary from a path. I guess you could use `os.Executable()` to get the location of the current binary, but there could be permission issues, etc? I think I prefer embedding the commit id in the build the way is done in this PR then.

**Comment by yaslama** [comment]
> With this you need to read the binary from a path. I guess you could use `os.Executable()` to get the location of the current binary, but there could be permission issues, etc? I think I prefer embedding the commit id in the build the way is done in this PR then.

From https://pkg.go.dev/runtime/debug#BuildSetting I can understand that vcs.modified can be directly obtained using ReadBuildInfo unless I am mistaken.

**Comment by JssDWt** [comment]
@yaslama I've updated the CommitHash variable to be taken from the build.
Also I added a makefile in order to still be able to set the tag. (nice if the tag is in the log too)
The CI now uses the makefile to build the release.

**Review by yaslama — APPROVED** [review]

**Pull request merged**
